<a href="https://colab.research.google.com/github/balamanipedakota/Assignment-/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def square_elements(arr):
  return np.square(arr)

my_array = np.array([1,2,3,4,5])
squared_array = square_elements(my_array)
print("original array:",my_array)
print("squared array:",squared_array)


original array: [1 2 3 4 5]
squared array: [ 1  4  9 16 25]


In [ ]:
import numpy as bala

b = bala.array([6,7,8,9,5])
print("matrix:\n",b)
print(f"shape:{b.shape}")
print(f"number of dimentions[]({b.ndim})")

matrix:
 [6 7 8 9 5]
shape:(5,)
number of dimentions[](1)


In [ ]:
import numpy as np

def square_elements(arr):
  return np.square(arr)

my_array = np.array([6,7,8,9,5])
squared_array = square_elements(my_array)
print("original array:",my_array)
print("squared array:",squared_array)

original array: [6 7 8 9 5]
squared array: [36 49 64 81 25]


In [ ]:
#1.temparature data analysis
import numpy as np
weekly_temps = np.array([22,24,25,23,26,28,27])
print("first 3 days:",weekly_temps[:3])

first 3 days: [22 24 25]


In [ ]:
#2.sensor data simulation
import numpy as np
sensor_readings = np.array([[21.5,22.0,np.nan,23.1,24.2,np.nan,25.0],[20.0,np.nan,21.5,22.3,np.nan,23.5,24.0]])
sensor_readings[np.isnan(sensor_readings)] = 0
print("\nsensor readings (nan replaced with 0):\n",sensor_readings)



sensor readings (nan replaced with 0):
 [[21.5 22.   0.  23.1 24.2  0.  25. ]
 [20.   0.  21.5 22.3  0.  23.5 24. ]]


In [ ]:
#3.inventory management
import numpy as np
product_ids = np.array([101,105,112,108])
all_bins = np.concatenate([product_ids,product_ids])
print("\ncombined bins:",all_bins)


combined bins: [101 105 112 108 101 105 112 108]


In [ ]:
#4.quarterly sales report
import numpy as np
q1_sales = np.array([500,520,550])
q2_sales = np.array([580,600,620])
sales_report = np.vstack((q1_sales,q2_sales))
print("\nquarterly sales report:\n",sales_report)


quarterly sales report:
 [[500 520 550]
 [580 600 620]]


In [ ]:
#5.finding high performers
import numpy as np
scores = np.array([85,92,78,88,95,76])
high_scores = scores[scores>=90]
print("\nhigh performers(>=90):",high_scores)



high performers(>=90): [92 95]
